- hosts: all
  gather_facts: false
  vars_files:
    - secrets.yml
  remote_user: "{{ user }}"
  become_user: "{{ user }}"
  tasks:
    - name: Pull image and run
      community.docker.docker_compose:
        project_src: /Users/{{ user }}/Server
        state: present
        pull: true
