- hosts: all
  vars_files:
    - secrets.yml
  remote_user: "{{ user }}"
  become_user: "{{ user }}"
  tasks:
    - name: Pull Docker Image
      become: True
      shell: docker compose pull leg3nd-pillar
      args:
        chdir: /Users/{{ user }}/Server
        executable: /bin/zsh
    - name: Restart Container
      become: True
      shell: docker compose up -d leg3nd-pillar --force-recreate
      args:
        chdir: /Users/{{ user }}/Server
        executable: /bin/zsh
