- hosts: all
  vars_files:
    - secrets.yml
  remote_user: "{{ user }}"
  tasks:
    - name: Pull Docker Image
      shell: /usr/local/bin/docker compose pull leg3nd-pillar
      args:
        chdir: /Users/{{ user }}/Server
        executable: /bin/zsh
    - name: Restart Container
      shell: /usr/local/bin/docker compose up -d leg3nd-pillar --force-recreate
      args:
        chdir: /Users/{{ user }}/Server
        executable: /bin/zsh
