- hosts: all
  vars_files:
    - secrets.yml
  remote_user: "{{ user }}"
  become_user: "{{ user }}"
  tasks:
    - name: Login to Private Registry
      become: True
      shell: /usr/local/bin/docker login {{ registry_host }} -u {{ registry_user }} -p {{ registry_password }}
      args:
        chdir: /Users/{{ user }}/Server
        executable: /bin/zsh
    - name: Pull Docker Image
      become: True
      shell: /usr/local/bin/docker compose pull leg3nd-pillar
      args:
        chdir: /Users/{{ user }}/Server
        executable: /bin/zsh
    - name: Restart Container
      become: True
      shell: /usr/local/bin/docker compose up -d leg3nd-pillar --force-recreate
      args:
        chdir: /Users/{{ user }}/Server
        executable: /bin/zsh
